In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
df = load_breast_cancer()

In [4]:
bc = pd.DataFrame(df.data, columns=df.feature_names)

In [5]:
bc.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X, y = bc.iloc[:, 1:].values, bc.iloc[:, 0].values

In [8]:
bc.iloc[0]

mean radius                  17.990000
mean texture                 10.380000
mean perimeter              122.800000
mean area                  1001.000000
mean smoothness               0.118400
mean compactness              0.277600
mean concavity                0.300100
mean concave points           0.147100
mean symmetry                 0.241900
mean fractal dimension        0.078710
radius error                  1.095000
texture error                 0.905300
perimeter error               8.589000
area error                  153.400000
smoothness error              0.006399
compactness error             0.049040
concavity error               0.053730
concave points error          0.015870
symmetry error                0.030030
fractal dimension error       0.006193
worst radius                 25.380000
worst texture                17.330000
worst perimeter             184.600000
worst area                 2019.000000
worst smoothness              0.162200
worst compactness        

In [9]:
type(bc.iloc[0])

pandas.core.series.Series

In [10]:
type(bc.iloc[[0,1]])

pandas.core.frame.DataFrame

In [11]:
bc.iloc[:3]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   
2        19.69         21.25           130.0     1203.0          0.10960   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   
2                 0.05999  ...         23.57          25.53            152.5   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 30 columns]

In [12]:
bc.iloc[2:5]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
2        19.69         21.25          130.00     1203.0           0.1096   
3        11.42         20.38           77.58      386.1           0.1425   
4        20.29         14.34          135.10     1297.0           0.1003   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
2            0.1599          0.1974               0.1279         0.2069   
3            0.2839          0.2414               0.1052         0.2597   
4            0.1328          0.1980               0.1043         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[3 rows x 30 columns]

In [13]:
bc.iloc[2:5:2]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
2        19.69         21.25           130.0     1203.0           0.1096   
4        20.29         14.34           135.1     1297.0           0.1003   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
2            0.1599          0.1974               0.1279         0.2069   
4            0.1328          0.1980               0.1043         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
2                 0.05999  ...         23.57          25.53            152.5   
4                 0.05883  ...         22.54          16.67            152.2   

   worst area  worst smoothness  worst compactness  worst concavity  \
2      1709.0            0.1444             0.4245           0.4504   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
2                0.2430          0.3613                  0.08758  
4                0.1625          0.2364                  0.07678  

[2 rows x 30 columns]

In [17]:
bc.iloc[:2, 1:3]

mean texture  mean perimeter
0         10.38           122.8
1         17.77           132.9

In [15]:
bc.iloc[:]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [18]:
bc.iloc[:3, 0]

0    17.99
1    20.57
2    19.69
Name: mean radius, dtype: float64

In [19]:
X_train, X_test, y_train, y_set =\
    train_test_split(X, y,
                    test_size=0.3,
                    random_state=0)

In [20]:
import numpy as np

In [21]:
A, b = np.arange(10).reshape((5,2)), range(5)

In [22]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
b

range(0, 5)

In [24]:
print(b)

range(0, 5)


In [26]:
list(b)

[0, 1, 2, 3, 4]

In [33]:
A_train, A_test, b_train, b_test =\
    train_test_split(A, b, test_size=0.33, random_state=42)

In [34]:
A_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [35]:
b_train

[2, 0, 3]

In [36]:
A_test

array([[2, 3],
       [8, 9]])

In [37]:
b_test

[1, 4]

In [38]:
train_test_split(b, shuffle=False)

[[0, 1, 2], [3, 4]]

In [39]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
scale = MinMaxScaler()

In [41]:
X_train_minmax = scale.fit_transform(X_train)

In [42]:
X_test_minmax = scale.fit_transform(X_test)

In [43]:
X_test_minmax

array([[0.34313725, 0.3853298 , 0.25342006, ..., 0.704811  , 0.51654939,
        0.60791158],
       [0.5087535 , 0.34230478, 0.24081277, ..., 0.20635739, 0.21918165,
        0.10738802],
       [0.17296919, 0.39433283, 0.28681599, ..., 0.28233677, 0.13891061,
        0.09831297],
       ...,
       [0.27871148, 0.38618271, 0.26300966, ..., 0.44123711, 0.32473286,
        0.36835369],
       [0.37990196, 0.35310842, 0.2463117 , ..., 0.19292096, 0.26948137,
        0.09226294],
       [0.39285714, 0.10452995, 0.05713519, ..., 0.08810997, 0.21683607,
        0.17777778]])

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
std_scale = StandardScaler()

In [46]:
X_train_stdscale = std_scale.fit_transform(X_train)

In [47]:
X_test_stdscale = std_scale.fit_transform(X_test)

In [48]:
X_test_stdscale

array([[ 0.22140254, -0.10696857, -0.26045399, ...,  1.39677786,
         1.14404645,  1.44477141],
       [ 1.26339611, -0.30309994, -0.32019212, ..., -0.80720664,
        -0.82315205, -0.90738698],
       [-0.84922934, -0.06592787, -0.10221151, ..., -0.47125285,
        -1.35417496, -0.9500342 ],
       ...,
       [-0.18393957, -0.10308051, -0.21501488, ...,  0.23134793,
        -0.12489141,  0.31899407],
       [ 0.45271189, -0.2538511 , -0.29413613, ..., -0.86661774,
        -0.49040068, -0.97846568],
       [ 0.53422091, -1.38700657, -1.19052576, ..., -1.33005467,
        -0.83866895, -0.57659762]])