In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(0, 10)

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,5))*8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(5)

array([0.15763196, 0.27906328, 0.09754042, 0.62240961, 0.45052251])

In [9]:
np.random.rand(3,3)

array([[0.14074688, 0.15975349, 0.41519309],
       [0.82229212, 0.28464244, 0.09060941],
       [0.88433531, 0.47637509, 0.42235465]])

In [10]:
np.random.randn(10)

array([-1.26659808,  0.51777596, -0.32830352, -1.66861098, -1.23935195,
       -0.03664702,  0.23795469,  0.39686923,  0.58693946, -0.78142804])

In [11]:
np.random.seed(5)

In [12]:
np.random.randint(1,100,10)

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [13]:
x = np.arange(25)

In [14]:
x.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
rand_x = np.random.randint(0,50,10)
rand_x

array([12, 15, 49, 39, 16, 27, 44, 13, 11,  1])

In [16]:
rand_x.max()

49

In [17]:
rand_x.argmax()

2

In [18]:
rand_x.shape

(10,)

In [19]:
rand_x.dtype

dtype('int32')

In [20]:
a[5]

5

In [21]:
a[2:7]

array([2, 3, 4, 5, 6])

In [22]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
a[:5]

array([0, 1, 2, 3, 4])

In [24]:
a[:5] = 20
a

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [25]:
a_copy = a.copy() 

In [26]:
mat = np.array([[10,20,30], [40,50,60], [70,80,90]])

In [27]:
mat[1]

array([40, 50, 60])

In [28]:
mat[1][2]

60

In [29]:
mat[1,2]

60

In [30]:
mat[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [31]:
mat[:2,1:]

array([[20, 30],
       [50, 60]])

In [32]:
x = np.arange(0,10)

In [33]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
bool_x = x < 5

In [35]:
x[bool_x]

array([0, 1, 2, 3, 4])

In [36]:
x+x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
x-x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
x*x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
x+15

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
x*50

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [41]:
x/x

<ipython-input-41-5b73abf0f85e>:1: RuntimeWarning: invalid value encountered in true_divide
  x/x


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
1/x

<ipython-input-42-98f9819de3e3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/x


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [43]:
x**5

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049], dtype=int32)

In [44]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [45]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [46]:
np.log(x)

<ipython-input-46-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [47]:
labels = ['a','b','c']
my_data = [10,20,30]
array = np.array(my_data)
d = {'a': 10, 'b': 20, 'c': 30}

In [48]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [49]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [50]:
pd.Series(array, labels)

a    10
b    20
c    30
dtype: int32

In [51]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [52]:
np.random.seed(10)

In [53]:
df = pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [54]:
df['W']

A    1.331587
B    0.621336
C    0.004291
D   -0.965066
E   -1.136602
Name: W, dtype: float64

In [55]:
type(df['W'])

pandas.core.series.Series

In [56]:
df[['W','Y']]

W         Y
A  1.331587 -1.545400
B  0.621336  0.265512
C  0.004291  0.433026
D -0.965066  0.228630
E -1.136602  1.484537

In [57]:
df['yeni'] = df['W'] + df['Y']

In [58]:
df

W         X         Y         Z      yeni
A  1.331587  0.715279 -1.545400 -0.008384 -0.213814
B  0.621336 -0.720086  0.265512  0.108549  0.886848
C  0.004291 -0.174600  0.433026  1.203037  0.437318
D -0.965066  1.028274  0.228630  0.445138 -0.736436
E -1.136602  0.135137  1.484537 -1.079805  0.347935

In [61]:
df.drop('yeni', axis=1, inplace=True)

In [62]:
df

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [63]:
df.drop('E')

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138

In [64]:
df.drop('E', inplace=True)

In [65]:
df

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138

In [66]:
df.loc['A']

W    1.331587
X    0.715279
Y   -1.545400
Z   -0.008384
Name: A, dtype: float64

In [67]:
df.iloc[2]

W    0.004291
X   -0.174600
Y    0.433026
Z    1.203037
Name: C, dtype: float64

In [68]:
df.loc['C', 'Z']

1.203037373812212

In [69]:
df.loc[['A', 'D'], ['X', 'Z']]

X         Z
A  0.715279 -0.008384
D  1.028274  0.445138

In [71]:
booldf = df > 0

In [72]:
df['W'] > 0

A     True
B     True
C     True
D    False
Name: W, dtype: bool

In [75]:
df[df['W'] > 0][['Y', 'Z']]

Y         Z
A -1.545400 -0.008384
B  0.265512  0.108549
C  0.433026  1.203037

In [77]:
df[(df['W'] > 0) & (df['Z']>1)]

W       X         Y         Z
C  0.004291 -0.1746  0.433026  1.203037

In [78]:
df[(df['W'] > 0) | (df['Z']>1)]

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037

In [79]:
df.reset_index()

index         W         X         Y         Z
0     A  1.331587  0.715279 -1.545400 -0.008384
1     B  0.621336 -0.720086  0.265512  0.108549
2     C  0.004291 -0.174600  0.433026  1.203037
3     D -0.965066  1.028274  0.228630  0.445138

In [83]:
sehir = 'Ankara Istanbul Izmir Bursa'.split()

In [84]:
sehir

['Ankara', 'Istanbul', 'Izmir', 'Bursa']

In [85]:
df['Sehir'] = sehir

In [86]:
df

W         X         Y         Z     Sehir
A  1.331587  0.715279 -1.545400 -0.008384    Ankara
B  0.621336 -0.720086  0.265512  0.108549  Istanbul
C  0.004291 -0.174600  0.433026  1.203037     Izmir
D -0.965066  1.028274  0.228630  0.445138     Bursa

In [88]:
df.set_index('Sehir')

W         X         Y         Z
Sehir                                           
Ankara    1.331587  0.715279 -1.545400 -0.008384
Istanbul  0.621336 -0.720086  0.265512  0.108549
Izmir     0.004291 -0.174600  0.433026  1.203037
Bursa    -0.965066  1.028274  0.228630  0.445138

In [90]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index_mul = pd.MultiIndex.from_tuples(hier_index)

In [91]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [92]:
hier_index_mul

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [93]:
df = pd.DataFrame(np.random.randn(6,2), hier_index_mul, ['A', 'B'])
df

A         B
G1 1 -1.977728 -1.743372
   2  0.266070  2.384967
   3  1.123691  1.672622
G2 1  0.099149  1.397996
   2 -0.271248  0.613204
   3 -0.267317 -0.549309

In [94]:
df.loc['G1'].loc[1]

A   -1.977728
B   -1.743372
Name: 1, dtype: float64

In [95]:
df.index.names = ['Grup', 'Sayi']

In [96]:
df

A         B
Grup Sayi                    
G1   1    -1.977728 -1.743372
     2     0.266070  2.384967
     3     1.123691  1.672622
G2   1     0.099149  1.397996
     2    -0.271248  0.613204
     3    -0.267317 -0.549309

In [97]:
df.xs('G1')

A         B
Sayi                    
1    -1.977728 -1.743372
2     0.266070  2.384967
3     1.123691  1.672622

In [99]:
df.xs(2, level='Sayi')

A         B
Grup                    
G1    0.266070  2.384967
G2   -0.271248  0.613204

In [100]:
d = {'A': [1,2,np.nan], 'B': [np.nan, 3, np.nan], 'C': [4,5,6]}

In [101]:
df = pd.DataFrame(d)

In [102]:
df

A    B  C
0  1.0  NaN  4
1  2.0  3.0  5
2  NaN  NaN  6

In [103]:
df.dropna()

A    B  C
1  2.0  3.0  5

In [104]:
df.dropna(axis=1)

C
0  4
1  5
2  6

In [105]:
df.dropna(thresh=2)

A    B  C
0  1.0  NaN  4
1  2.0  3.0  5

In [106]:
df.fillna(value='full')

A     B  C
0     1  full  4
1     2     3  5
2  full  full  6

In [107]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [109]:
data = {'Sirket': ['TURKCELL', 'TURKCELL', 'VODAFONE', 'VODAFONE', 'TELEKOM','TELEKOM'],
        'Kisi': ['Mehmet', 'Busra', 'Selim', 'Caner', 'Gamze', 'Merve'],
        'Satis': [250, 325, 152, 645, 468, 525]}

In [110]:
df = pd.DataFrame(data)

In [111]:
df

Sirket    Kisi  Satis
0  TURKCELL  Mehmet    250
1  TURKCELL   Busra    325
2  VODAFONE   Selim    152
3  VODAFONE   Caner    645
4   TELEKOM   Gamze    468
5   TELEKOM   Merve    525

In [112]:
sirket = df.groupby('Sirket')

In [113]:
sirket.mean()

Satis
Sirket         
TELEKOM   496.5
TURKCELL  287.5
VODAFONE  398.5

In [114]:
sirket.sum().loc['TURKCELL']

Satis    575
Name: TURKCELL, dtype: int64

In [116]:
df.groupby('Sirket').count()

Kisi  Satis
Sirket               
TELEKOM      2      2
TURKCELL     2      2
VODAFONE     2      2

In [117]:
df.groupby('Sirket').describe()

Satis                                                        
         count   mean         std    min     25%    50%     75%    max
Sirket                                                                
TELEKOM    2.0  496.5   40.305087  468.0  482.25  496.5  510.75  525.0
TURKCELL   2.0  287.5   53.033009  250.0  268.75  287.5  306.25  325.0
VODAFONE   2.0  398.5  348.603643  152.0  275.25  398.5  521.75  645.0